export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const ADD_PASSWORD_RESET = 'ADD_PASSWORD_RESET'
export const ADD_PASSWORD_RESET_SUCCESS = 'ADD_PASSWORD_RESET_SUCCESS'
export const ADD_PASSWORD_RESET_ERROR = 'ADD_PASSWORD_RESET_ERROR'

export const SAVE_TOKEN = 'SAVE_TOKEN'

export const SIGN_UP_SUCCESSED = 'SIGN_UP_SUCCESSED'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED'

export const GET_POST = 'GET_POST'
export const GET_POST_SUCCES = 'GET_POST_SUCCESS'
export const GET_POST_ERROR = 'GET_POST_ERROR'

export const GET_COMMENT = 'GET_COMMENT'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR'

export const GET_MORE_POST = 'GET_MORE_POST'
export const GET_MORE_POST_SUCCESS = 'GET_MORE_POST_SUCCESS'
export const GET_MORE_POST_ERROR = 'GET_MORE_POST_ERROR'

export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK'
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS'
export const SIGN_UP_FACEBOOK = 'SIGN_UP_FACEBOOK'
export const SIGN_UP_FACEBOOK_SUCCESS = 'SIGN_UP_FACEBOOK_SUCCESS'
export const SIGN_UP_FACEBOOK_ERROR = 'SIGN_UP_FACEBOOK_ERRROR'

export const PROFILE_USER_POST_REQUESTED = 'PROFILE_USER_REQUESTED'
export const PROFILE_USER_POST_SUCCESS = 'PROFILE_USER_POST_SUCCESS'
export const PROFILE_USER_POST_FAILED = 'PROFILE_USER_POST_FAILED'

export const GET_POST_USER_REQUESTED = 'GET_POST_USER_REQUESTED'
export const GET_POST_USER_SUCCESS = 'GET_POST_USER_SUCCESS '
export const GET_POST_USER_FAILED = 'GET_POST_USER_FAILED'

export const LIKE = 'LIKE'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_ERROR = 'LIKE_ERROR'

export const GET_POST_DETAIL = 'GET_POST_DETAIL'
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS'
export const GET_POST_DETAIL_ERROR = 'GET_POST_DETAIL_ERROR'

export const GET_MORE_COMMENT = 'GET_MORE_COMMENT'
export const GET_MORE_COMMENT_SUCCESS = 'GET_MORE_COMMENT_SUCCESS'
export const GET_MORE_COMMENT_ERROR = 'GET_MORE_COMMENT_ERROR'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_POST_REQUESTED = 'UPLOAD_POST_REQUESTED'
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS'
export const UPLOAD_POST_FAILED = 'UPLOAD_POST_FAILED'

export const GET_MORE_POST_USER_REQUESTED = 'GET_MORE_POST_USER_REQUESTED'
export const GET_MORE_POST_USER_SUCCESS = 'GET_MORE_POST_USER_SUCCESS'
export const GET_MORE_POST_USER_FAILED = 'GET_MORE_POST_USER_FAILED'
